// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz3sVCkPlGbYyd6xh585lkh0KgaUqtdBY',
    appId: '1:506827596922:web:625e96613424e4488e87c3',
    messagingSenderId: '506827596922',
    projectId: 'ecommerce-c79bb',
    authDomain: 'ecommerce-c79bb.firebaseapp.com',
    storageBucket: 'ecommerce-c79bb.appspot.com',
    measurementId: 'G-L38CYTJVXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMO3gKZC9_GFrEQ_LJbRAV9aJierz-WFw',
    appId: '1:506827596922:android:e007ad09f6ace0118e87c3',
    messagingSenderId: '506827596922',
    projectId: 'ecommerce-c79bb',
    storageBucket: 'ecommerce-c79bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe_hk_diTR9v4TDkUrNk1liymNpBSEHxE',
    appId: '1:506827596922:ios:e5eac695bbd537948e87c3',
    messagingSenderId: '506827596922',
    projectId: 'ecommerce-c79bb',
    storageBucket: 'ecommerce-c79bb.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe_hk_diTR9v4TDkUrNk1liymNpBSEHxE',
    appId: '1:506827596922:ios:7a04ef9e9f05660e8e87c3',
    messagingSenderId: '506827596922',
    projectId: 'ecommerce-c79bb',
    storageBucket: 'ecommerce-c79bb.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
